### ISSUE TITLE
Unclear Whereabouts of Web Tools Codebase

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-web-tools-api#47]
Unlike VEP, it is not clear where the code for tools such as Variant Recoder is at. Also, the Helpdesk is closed.
![image](https://github.com/user-attachments/assets/b09ebb01-ec87-4172-8485-1eb95be76fa1)

**Comment by azangru** [comment]
Hi @DarioS,

This is the repository of the tools api code for the next version of the Ensembl website (currently at beta.ensembl.org). It does not have full feature parity with the tools available on the current Ensembl website (www.ensembl.org). If you are interested in those tools, their code (in Perl) is distributed between https://github.com/Ensembl/public-plugins and other repositories, such as https://github.com/Ensembl/ensembl-vep for Variant Recoder.

If you would like to contact Ensembl Helpdesk, please use the contact form on the [Ensembl blog site](https://www.ensembl.info) for now.
